### ISSUE TITLE
Dojo build plugin is removing escapes in CSS rules

### ISSUE THREAD

**Issue by stdavis** [kriszyp/xstyle#38]
If I use the `xstyle/build/amd-css` plugin rules that look like this:

``` css
.glyphicon-glass:before {
  content: "\e001";
}
```

look like this after going through the plugin:

``` css
.glyphicon-glass:before {content: "e001";}
```

This obviously causes problems in the built version of my application.

I made an [attempt at fixing the problem](https://github.com/kriszyp/xstyle/pull/36) but was unsuccessful.
