### ISSUE TITLE
Media queries incorrectly minified via build plugin

### ISSUE THREAD

**Issue by stdavis** [kriszyp/xstyle#39]
When I run this code through the build plugin

``` css
@media print {
    .report .btn, 
    .current-location {
        visibility: hidden;
        display: none;
    }
}
```

it is incorrectly minified to this

``` css
@media print .report .btn, .current-location {visibility:hidden;display:none;}
```

it should be minified to something like this

``` css
@media print {.report .btn, .current-location {visibility:hidden;display:none;}}
```
