### ISSUE TITLE
Unicode codes are being parsed into characters

### ISSUE THREAD

**Issue by stdavis** [kriszyp/xstyle#40]
Having issues with unicode strings again with the latest version.

This

``` css
.glyphicon-search:before {
content: "\e003";
}
```

is being built into this:

``` css
.glyphicon-search:before {
content: "";
}
```
